### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by simonqbs** [asbjornenge/rainbow-dock-populator#2]
I've been using rainbow-dock/rainbow-dock-populator over the weekend to replace skydock and it's working great. No more dns resolutions failing. :) Anyway, here's some suggestions to make it even better/skydock like:
- In addition to `--dockerhost` perhaps add a `--dockersocket` option?
- Fetch rainbow-dock's IP address so we don't need to use `--apihost`. Just specify rainbow-dock's container name in maybe a `--apiname` option.
- Clean container image and name before adding them to rainbow-dock. Example:
  I have a container that is named `redis_123` and using image `redis:2.8`
  
  Expected domain name:
  redis-123.redis.internal.domain
  
  Actual domain name:
  redis_123.redis.2.8.internal.domain
- Use `node:0.11-slim` -- it's more than half the size of `node:0.11`

**Comment by asbjornenge** [comment]
@simonqbs thanks for some great suggestions! I'll get on all of those real soon :+1: I'll ping you here when I have something you can test :smile_cat: 

Thanks ALOT for the node:0.11-slim tip, didn't even know about that one!! :rocket: 

Also, I haven't decided if entrypoint args (--dockerhost) or ENV variables are the best way to go for passing arguments to ... well to all my docker containers really. What do you think? Is there a clear distinction between what args should be entrypoint args and what args should be ENV variables?

**Comment by simonqbs** [comment]
That sounds great. About env vs args, I usually use env for passwords, api
keys, path to config files etc.

**Comment by simonqbs** [comment]
I'm having problems resolving hosts without subdomain, see example. If I run container with `--dns 8.8.8.8` it works just fine.

```
root@18e6f4f5ab9a:/# wget github.com
--2015-01-14 12:56:39--  http://github.com/
Resolving github.com (github.com)... failed: No address associated with hostname.
wget: unable to resolve host address `github.com'
root@18e6f4f5ab9a:/# wget www.github.com
--2015-01-14 12:56:45--  http://www.github.com/
Resolving www.github.com (www.github.com)... 192.30.252.129
Connecting to www.github.com (www.github.com)|192.30.252.129|:80... connected.
```

**Comment by asbjornenge** [comment]
@simonqbs hm, if it's a bug it would be something in [rainbow-dns](https://github.com/asbjornenge/rainbow-dns). It not sure, but could it be related to the --ipv4-for-ipv6 flag? Are you using --fwdhost 8.8.8.8 for the rainbow-dock container?

Any log output for the rainbow-dock container?

**Comment by simonqbs** [comment]
I've tried with and without `--ipv4-for-ipv6` -- no difference. Using the same arguments as in the readme. Rainbow-dock container is silent.
For what it's worth here's dig output using rainbow-dns vs google dns (can it have something to do with WARNING: recursion requested but not available?):

```
root@46f622f0c379:/# dig github.com

; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57701
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             19      IN      A       192.30.252.131

;; Query time: 25 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Wed Jan 14 15:56:27 2015
;; MSG SIZE  rcvd: 44

root@46f622f0c379:/# dig @8.8.8.8 github.com                                                                                                                            

; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> @8.8.8.8 github.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33601
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             28      IN      A       192.30.252.131

;; Query time: 16 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jan 14 15:57:16 2015
;; MSG SIZE  rcvd: 44
```

**Comment by asbjornenge** [comment]
I don't think the recursion warning should matter. And you should get that for both top level domains and sub domains...? And you can wget/curl sub domains still, right?

Since you can dig at rainbow-dns and get a proper A response back, it is quite weird that wget can't resolve the host. I tried github.com locally and it works fine for me. Only other time I've seen this (dig can get results but other apps can't resolve) is with that --ipv4-for-ipv6 bug.

Does it work if you force ipv4 mode?

```
curl github.com -I // resolve issues?
curl github.com -I -4 // still broken?
```

**Comment by asbjornenge** [comment]
I split your other requests into multiple issues. Let me know if you have any additional comments. I hope to get some work done on this today :smile:

**Comment by simonqbs** [comment]
Wget/curl works properly with subdomains. For top level domains it does work by forcing ipv4 mode.

**Comment by asbjornenge** [comment]
@simonqbs interesting! I'll take a close look :+1:

**Comment by asbjornenge** [comment]
@simonqbs I managed to track this one down (I think)!! Have a look at https://github.com/ioquatix/rubydns/issues/26#issuecomment-40167316

node:0.11-slim is based of debian:wheezy which is where I had that ipv4-for-ipv6 issue too! Seems like the resolver is fairly broken on that one :stuck_out_tongue_closed_eyes: 

Anyway, I documented it at asbjornenge/rainbow-dns#6 and will be pushing out a fix asap :+1: I'll also update the rainbow-dock images accordingly and ping back here when it's ready :grin:

**Comment by asbjornenge** [comment]
@simonqbs Alright! Pushed the update and triggered a new build on the :whale: hub. I also tagged this version, so you can <code>docker run asbjornenge/rainbow-dock:3.0.1</code> if you want to pin versions :+1: 

I'm going to close this issue, but feel free to re-open if you are still having issues :smile:
