### ISSUE TITLE
Clean container image and name

### ISSUE THREAD

**Issue by asbjornenge** [asbjornenge/rainbow-dock-populator#5]
Clean container image and name before adding them to rainbow-dock. Example:
I have a container that is named redis_123 and using image redis:2.8

Expected domain name:
redis-123.redis.internal.domain

Actual domain name:
redis_123.redis.2.8.internal.domain

**Comment by asbjornenge** [comment]
@simonqbs In my setup I actually want to be able to distinguish between versions/tags. However the current working is not good since version with . in them breaks up the grouping such that a query for 8.internal.domain could return multiple applications.

I propose two changes.
1. Create appropriate image-tag grouping (replace . with -)
   
   redis:2.8 -> name.redis-2-8.internal.domain
2. Disable this feature by default and add a flag to enable it
   
   --versiongroup=true

This way it works like skydock by default and I can enable the version grouping if I want :smile:

Thoughts?

**Comment by simonqbs** [comment]
Sure, that would work too. :)
